language: python
python: 3.7

branches:
  only:
    - master

install:
  - pip install -r requirements.txt

script:
  - python -m unittest discover tests
  - docker build
    -t jackneilp/flask-example:latest
    -t jackneilp/flask-example:$TRAVIS_BUILD_NUMBER .
